[project]
name = "foodcoop-shift-calendar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gcsa>=2.5.1",
    "playwright>=1.51.0",
    "pydantic>=2.11.2",
    "python-dotenv>=1.1.0",
    "uvloop>=0.21.0",
]
