services:
- type: cron
  name: foodcoop-shift-calendar
  runtime: docker
  repo: https://github.com/rexledesma/foodcoop-shift-calendar
  plan: standard
  envVars:
  - key: .env
    sync: false
  - key: credentials.json
    sync: false
  region: oregon
  schedule: '*/10 * * * *'
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
